### ISSUE TITLE
Cannot build Docker with `npm install -g`

### ISSUE THREAD

**Issue by alexei-led** [codefresh-io/dind#2]
It's not possible to build the following **valid** Dockerfile with Codefresh. 

```
FROM node:9-alpine
RUN npm install -g serverless
```

It's possible to build it locally with any Docker engine, including `codefresh/dind:17.12-v12` (our DinD)

**Comment by alexei-led** [comment]
very strange issue indeed

docker build for `node:8/9/10-alpine` based `Dockerfile` with `npm install -g <any_module>` fails with any Docker (or dind) engine running on Amazon M5 instances.

see related:
https://github.com/npm/npm/issues/20861
https://bitbucket.org/site/master/issues/16334/pipelines-failing-with-could-not-get-uid

**Comment by ccheshire** [comment]
I ran into the same issue after we upgraded to an m5 instance,
found a solution at https://github.com/npm/uid-number/issues/3#issuecomment-291362937

so I added
`RUN npm config set unsafe-perm true` to my Dockerfile before the npm install and everything works again

**Comment by masontikhonov** [comment]
Closing as stale.
