### ISSUE TITLE
Typo in repo description

### ISSUE THREAD

**Issue by nesl247** [codefresh-io/dind#6]
In the repo description you have `fro` instead of `for`.

![image](https://user-images.githubusercontent.com/1037526/58130166-685c8100-7be9-11e9-80dc-0c1e2cbd0087.png)

**Comment by masontikhonov** [comment]
Closing as stale (and fixed).
@nesl247 Is it still appropriate to apologize for the long response? 🙈

**Comment by nesl247** [comment]
Hey, no worries at all.
